#!/bin/bash 
SIZE=$1
NUM_RUNS=$2
TEST=$3
COUNTER=0
COUNTER2=0
until [  $COUNTER -gt $NUM_RUNS ]; do
  echo $COUNTER
  FLUIDDIR="/data/fluid_flow_steady_state_$SIZE"
  FLUIDDIR+="x"
  FLUIDDIR+="$SIZE"
  FLUIDDIR+="_$TEST"
  mkdir $FLUIDDIR
  FLUIDDIR+="/sample_$COUNTER"
  mkdir $FLUIDDIR
  for i in 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1
  do
    VDIR="$FLUIDDIR/v_$i"
    mkdir $VDIR
    VDIR+="/fluid_flow"
    #./generate_xiao_fluid_flow $SIZE $FLUIDDIR $CARDIR
    ./generate_xiao_fluid_flow $SIZE $VDIR $i
  done 
  let COUNTER+=1
done

#CARDIR="objs/obj_"
# CARDIR+="$(echo 0000$COUNTER | tail -c 4)"
# CARDIR+=".txt"
# echo $CARDIR
